version: '3.4'

services:
  testtaskfugr:
    container_name: testtaskfugr
    image: testtaskfugr
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
