version: '3.4'

services:
  test-task-fugr:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - '/app/node_modules'
      - '.:/app'
    stdin_open: true
